---
- name: Provision kiosk to run podman applications
  hosts: all
  become: true
  vars:
    systemd_units_dir: /etc/systemd/system/
    service_name: guiseai-apparel-logo-demo
    container_state: installed
    container_image: quay.io/hybridcloudpatterns/guiseai_apparel_logo_demo
    container_tag: "obf-v1.0.1"
    container_port_mapping: 5001:5001
    container_extra_params: ''
  tasks:
    - name: Configure kiosk mode on hmi devices
      ansible.builtin.import_role:
        name: kiosk_mode
    - name: Import container_lifecycle role
      ansible.builtin.import_role:
        name: container_lifecycle
